\include "lys/bk2_c3_r1.ly"
\pageBreak
\include "lys/bk2_c3_r2.ly"
%  \include "lys/bk2_c3_r3.ly"
%  \include "lys/bk2_c3_r4.ly"
%  \include "lys/bk2_c3_r5.ly"
%  \include "lys/bk2_c3_r6.ly"
%  \include "lys/bk2_c3_r7.ly"
%  \include "lys/bk2_c3_r8.ly"
%  \include "lys/bk2_c3_r9.ly"